name: Build Image

on:
  workflow_call:
    inputs:
      name-id:
        required: true
        type: string
      mods:
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Build ${{ inputs.name-id }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        build-args: mods=${{ inputs.mods }}
        push: true
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/squad:${{ inputs.name-id }}
        cache-to: inline
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/squad:${{ inputs.name-id }}"
