name: Common Build Init

on:
  workflow_call:

jobs:
  init-build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v3
  
    - name: Login To Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ vars.DOCKER_REGISTRY_URL }}"
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
  
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
