name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'
  push:
    branches:
      - Development

jobs:

  build_matrix:
    strategy:
      matrix:
        include:
          - name-id: latest
            mods: ""
          - name-id: mee-french-latest
            mods: "1959152751,2618610732"
          - name-id: tac-latest
            mods: "2924330335,2923657563,2914624834,2891780963,2922041761,2933029302"
          - name-id: tac-bots-latest
            mods: "2891780963"
    runs-on: self-hosted
    steps:
      - name: Init Build
        uses: ./.github/workflows/init.yml
        
      - name: Build
        uses: ./.github/workflows/buildImage.yml
        with:
          name-id: ${{ matrix.name-id }}
          mods: ${{ matrix.mods }}
