name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'
  push:
    branches:
      - Development

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login To Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ vars.DOCKER_REGISTRY_URL }}"
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Vanilla Squad Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/squad:latest
        cache-to: type=inline
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/squad:latest"


    - name: Build MEE-French Squad Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        build-args: |
          mods=1959152751,2618610732
        push: true
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/squad:mee-french-latest
        cache-to: type=inline
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/squad:mee-french-latest"
        
    - name: Build Tac Squad Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        build-args: |
          mods=2924330335,2923657563,2914624834,2891780963,2922041761,2933029302
        push: true
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/squad:tac-latest
        cache-to: type=inline
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/squad:tac-latest"
