name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'
  push:
    branches:
      - Development

jobs:

  build_matrix:
    strategy:
      matrix:
        include:
          - name-id: latest
            mods: ""
          - name-id: mee-french-latest
            mods: "1959152751,2618610732"
          - name-id: tac-latest
            mods: "2924330335,2923657563,2914624834,2891780963,2922041761,2933029302"
          - name-id: tac-bots-latest
            mods: "2891780963"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: "${{ vars.DOCKER_REGISTRY_URL }}"
          username: "${{ secrets.DOCKER_REGISTRY_USER }}"
          password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
          
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: mods=${{ matrix.mods }}
          push: true
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/squad:${{ matrix.name-id }}
          cache-to: inline
          tags: "${{ vars.DOCKER_REGISTRY_URL }}/squad:${{ matrix.name-id }}"
