name: Docker Image CI

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login To Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ vars.DOCKER_REGISTRY_URL }}"
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Vanilla Squad Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: "${{ secrets.DOCKER_REGISTRY_USER }}/squad:latest"


    - name: Build Vanilla Squad Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=registry,ref=user/squad:latest
        cache-to: type=inline
        tags: "${{ secrets.DOCKER_REGISTRY_USER }}/squad:latest"

